client/jsx/emails/EmailContainer.jsx
client/jsx/emails/EmailPagination.jsx
client/jsx/emails/EmailTable.jsx
client/jsx/emails/EmailTableRow.jsx
client/sass/components/_emailTable.sass
server/routes/api.js

add pagination on emailtable

---

client/jsx/MailRoadRouter.jsx
client/jsx/editor/DynamicEditor.jsx
server/routes/auth.js

fix silent auth failure

---

client/jsx/editor/EditorContainer.jsx
client/jsx/editor/editor-types/DefaultEditor.jsx
client/lib/pouchdb.js
server/routes/api.js

Fixes #21. Not as big of a change as I expected.

rename content to contents in lots of places

---

.gitignore
client/jsx/editor/DynamicEditor.jsx
client/jsx/editor/EditorContainer.jsx
client/jsx/editor/EditorTypeRow.jsx
client/jsx/editor/editor-types/EditorTypeSelect.jsx
client/jsx/editor/editor-types/EditorTypes.js
client/jsx/editor/editor-types/EventsCalendar.jsx
client/jsx/editor/editor-types/ItemTypes.js
client/jsx/media/MediaContainer.jsx
client/sass/components/_components.sass
client/sass/components/_eventsCalendar.sass
package.json
webpack.config.js

PR-30 add eventsCalendar component (#30) 

---

client/jsx/emails/EmailContainer.jsx
client/jsx/emails/EmailTable.jsx
client/jsx/emails/EmailTableRow.jsx
server/couchdb-views/EmailsByUpdatedDate.js

Add category to emailtable

---

client/jsx/editor/EditorContainer.jsx
client/jsx/modals/ExternalImageModal.jsx
client/jsx/modals/ImageGalleryModal.jsx

Add externalimagemodal

---

client/jsx/modals/ImageGalleryModal.jsx

As it were. Fixes #51 
Added autobinding to prop method

Easiest bugfix ever. Fixes #51.

---

client/jsx/emails/EmailContainer.jsx
client/jsx/emails/EmailPagination.jsx

PR-17 fix emailtable pagination

---

client/jsx/App.jsx
client/jsx/NavBar.jsx
client/jsx/NotificationContainer.jsx
client/jsx/editor/EditorContainer.jsx
client/jsx/emails/EmailControls.jsx
client/lib/pouchdb.js
client/sass/components/_components.sass
client/sass/components/_notificationContainer.sass

PR-36 implement notification system

---

client/jsx/editor/EditorContainer.jsx

PR-48 extract items from state to store in database

---

client/jsx/editor/EditorContainer.jsx
server/routes/api.js

PR-57 exclude dirs from mjml-templates

---

.env.sample
client/jsx/emails/EmailContainer.jsx
client/lib/logging.js
package.json
server/lib/index.js
server/routes/api.js
server/routes/auth.js
server/routes/s3.js

Fixes #11 
Still need to add logging in lots of clientside places, but otherwise it works.

PR-11 add logging

---

client/jsx/editor/DynamicEditor.jsx
client/jsx/editor/EditorContainer.jsx
client/jsx/editor/editor-types/DefaultEditor.jsx
client/jsx/editor/editor-types/EditorTypeSelect.jsx
client/jsx/editor/editor-types/EditorTypes.js
client/jsx/editor/editor-types/EventsCalendar.jsx
client/jsx/editor/editor-types/FlexibleImage.jsx
client/jsx/editor/editor-types/SingleImage.jsx
client/sass/components/_components.sass
client/sass/components/_eventsCalendar.sass
client/sass/components/_flexibleImage.sass
client/sass/components/_singleImage.sass
client/sass/components/_slateEditor.sass
client/sass/main.sass
client/sass/mixins/_mixins.sass
client/sass/variables/_colors.sass

add flexible image component, make some tweaks to singleimage

---

client/jsx/editor/EditorContainer.jsx
client/jsx/editor/EditorTypeContainer.jsx
client/jsx/editor/editor-types/FlexibleImage.jsx

PR-65 refactor editorTypeRow into component

---

client/jsx/editor/editor-types/SingleImage.jsx

PR-71 fix singleImage

---

.vscode/launch.json
config/paths.js
package.json
server/routes/auth.js

Fixes #73, it works for server side stuff but meh. figure out clientside later.

PR-73 vscode debugging

---

client/jsx/editor/EditorContainer.jsx

PR-70 redirect url on save

---

client/jsx/editor/EditorContainer.jsx
client/jsx/editor/editor-types/EditorTypes.js
client/jsx/editor/editor-types/SingleHeading.jsx
client/sass/components/_components.sass
client/sass/components/_singleHeading.sass

PR-77 add single heading

---

client/jsx/MailRoadRouter.jsx
client/jsx/editor/EditorContainer.jsx
client/jsx/editor/EditorMetaContainer.jsx
client/jsx/emails/EmailContainer.jsx
client/jsx/emails/EmailTable.jsx
client/jsx/emails/EmailTableRow.jsx
client/jsx/login/LoginForm.jsx
server/couchdb-views/emails.js
server/routes/api.js
server/routes/auth.js

PR-68 add author to EditorContainer

---

client/jsx/emails/EmailPagination.jsx

PR-80 fix pagination off-by-one

---

client/jsx/editor/EditorContainer.jsx
client/jsx/editor/EditorMetaContainer.jsx
client/jsx/editor/editor-types/EventsCalendar.jsx
client/jsx/editor/editor-types/SingleImage.jsx
client/sass/components/_eventsCalendar.sass

PR-66 fix controlled component warnings

---

client/jsx/editor/EditorControlsContainer.jsx

PR-93 editmode button state

---

server/lib/index.js

Pretty much a health check. Addresses issue #100 
Registered before the wildcard route that sends all other requests to React

healthcheck: register route for aws pinging

---

client/jsx/editor/EditorContainer.jsx
client/jsx/editor/EditorControlsContainer.jsx

PR-111 fix edit mode button

---

client/jsx/emails/EmailContainer.jsx
client/jsx/emails/EmailControls.jsx
client/jsx/emails/EmailTableRow.jsx
client/lib/utils.js
server/routes/api.js

Fixes #38 and #5 since I had duplicate tickets.

PR-38 fix checkbox copy/delete

---

package.json
server/lib/mci-couchdb.js
server/routes/api.js
test/spec/api-test.js

I moved a lot of the couchdb axios requests into a separate `mci-couchdb.js` file which gets required by our route handlers. Also added mucho tests
Helps in a couple ways:
- Allows us to isolate things by function and see where errors are really happening
- We can compose compound couchdb queries without have a nasty string of axios promises

Couchdb: separate module for db queries + MUCHO TESTS

---

client/jsx/editor/DynamicEditor.jsx
client/jsx/editor/EditorContainer.jsx
client/sass/components/_editorContainer.sass

Fixes #118 
Also added a confirm to delete popup.

PR-118 move drag/close buttons to side

---

client/__tests__/EmailTable-test.jsx
client/__tests__/__snapshots__/EmailTable-test.jsx.snap
client/__tests__/sanity.js
package.json

Making a PR here to get this into master. Let me know if any of the `package.json` changes break anything for you.
To run client tests:
```bash
npm run client-tests
```
Right now, only have one test that makes sure an email table actually creates a table with `n` rows

Baby client tests
